version: '3.8'

services:
  api:
    env_file:
        - .env
    depends_on:
      db:
        condition: service_healthy
    container_name: dev_api
    build: './api'
    environment:
      POSTGRES_DB: 
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_HOST: db
    ports:
      - 3000:3000
    volumes:
      - ./api/src:/usr/api/src

  db:
    container_name: dev_db  
    restart: always
    image: "postgres:latest"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
    ports:
      - 5432:5432
    volumes:
      - ./dbData:/var/lib/postgresql/data